In [153]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [154]:
import pickle

In [155]:
df=pd.read_csv('Maruti.csv')
y=df['selling_price']

In [156]:
df.head()

year  selling_price  km_driven    fuel seller_type transmission  \
0  2007          60000      70000  Petrol  Individual       Manual   
1  2007         135000      50000  Petrol  Individual       Manual   
2  2007         140000     125000  Petrol  Individual       Manual   
3  2017         365000      78000     CNG  Individual       Manual   
4  2007          60000      70000  Petrol  Individual       Manual   

         owner Car_Company         Model_Name  
0  First Owner      Maruti             800 AC  
1  First Owner      Maruti  Wagon R LXI Minor  
2  First Owner      Maruti      Alto LX BSIII  
3  First Owner      Maruti  Celerio Green VXI  
4  First Owner      Maruti             800 AC

In [157]:
df.drop('Car_Company',axis=1,inplace=True)

In [158]:
df.head()

year  selling_price  km_driven    fuel seller_type transmission  \
0  2007          60000      70000  Petrol  Individual       Manual   
1  2007         135000      50000  Petrol  Individual       Manual   
2  2007         140000     125000  Petrol  Individual       Manual   
3  2017         365000      78000     CNG  Individual       Manual   
4  2007          60000      70000  Petrol  Individual       Manual   

         owner         Model_Name  
0  First Owner             800 AC  
1  First Owner  Wagon R LXI Minor  
2  First Owner      Alto LX BSIII  
3  First Owner  Celerio Green VXI  
4  First Owner             800 AC

In [85]:
df[df['Model_Name']=='800 AC']['selling_price'].mean()

94347.82608695653

In [159]:
model_names=list(df['Model_Name'].unique())

In [161]:
len(model_names)

303

In [162]:
avg_prices=[]
for i in model_names:
    avg_prices.append(df[df['Model_Name']==i]['selling_price'].mean())

In [163]:
models_df=pd.DataFrame({'Model_name':model_names,'Avg_selling_price':avg_prices})

In [164]:
models_df

Model_name  Avg_selling_price
0                   800 AC       94347.826087
1        Wagon R LXI Minor      144416.666667
2            Alto LX BSIII      117500.000000
3        Celerio Green VXI      365000.000000
4            Ciaz VXi Plus      585000.000000
..                     ...                ...
298  Alto 800 LXI Optional      335000.000000
299  Alto 800 LXI Opt BSIV      315000.000000
300  Alto K10 VXI Optional      285000.000000
301        Ertiga SHVS LDI      500000.000000
302              Swift LDI      400000.000000

[303 rows x 2 columns]

In [166]:
for i in range(0,302):
    models_dict.update([(model_names[i],avg_prices[i])])

In [165]:
models_dict={}

In [167]:
models_dict

{'800 AC': 94347.82608695653,
 'Wagon R LXI Minor': 144416.66666666666,
 'Alto LX BSIII': 117500.0,
 'Celerio Green VXI': 365000.0,
 'Ciaz VXi Plus': 585000.0,
 'Vitara Brezza ZDi Plus AMT': 887500.0,
 'Wagon R VXI BS IV with ABS': 259999.5,
 'Wagon R VXI BS IV': 305344.7931034483,
 'Alto LXi': 123553.17021276595,
 'Swift Dzire VDI Optional': 722500.0,
 'Eeco 5 Seater AC BSIV': 346222.22222222225,
 'Omni Maruti Omni MPI STD BSIII 5-STR W/ IMMOBILISER': 310000.0,
 'Swift ZDi BSIV': 552500.0,
 'Swift 1.3 VXi': 165727.27272727274,
 'Ciaz 1.3 Delta': 750000.0,
 'SX4 Zxi BSIII': 228333.33333333334,
 'SX4 ZXI MT BSIV': 236666.66666666666,
 'Swift Dzire VDI': 511463.73913043475,
 'SX4 Vxi BSIII': 110000.0,
 'Ertiga VDI': 543333.1666666666,
 'Zen LX': 72636.36363636363,
 'Baleno Delta 1.2': 565666.6666666666,
 'Swift Vdi BSIII': 226666.58333333334,
 'Ertiga SHVS VDI': 738500.0,
 '800 Std': 85041.66666666667,
 '800 AC BSIII': 89000.0,
 'Ciaz VDi Plus': 592500.0,
 'Vitara Brezza VDi': 757250.0,


In [168]:
Newf_df=df.copy()

In [169]:
Newf_df.head()

year  selling_price  km_driven    fuel seller_type transmission  \
0  2007          60000      70000  Petrol  Individual       Manual   
1  2007         135000      50000  Petrol  Individual       Manual   
2  2007         140000     125000  Petrol  Individual       Manual   
3  2017         365000      78000     CNG  Individual       Manual   
4  2007          60000      70000  Petrol  Individual       Manual   

         owner         Model_Name  
0  First Owner             800 AC  
1  First Owner  Wagon R LXI Minor  
2  First Owner      Alto LX BSIII  
3  First Owner  Celerio Green VXI  
4  First Owner             800 AC

In [170]:
Newf_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1280 entries, 0 to 1279
Data columns (total 8 columns):
year             1280 non-null int64
selling_price    1280 non-null int64
km_driven        1280 non-null int64
fuel             1280 non-null object
seller_type      1280 non-null object
transmission     1280 non-null object
owner            1280 non-null object
Model_Name       1280 non-null object
dtypes: int64(3), object(5)
memory usage: 80.1+ KB


In [171]:
Newf_df['Model_Name']=Newf_df['Model_Name'].map(models_dict)

In [130]:
df['fuel'].unique()

array(['Petrol', 'CNG', 'Diesel', 'LPG'], dtype=object)

In [131]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [132]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [133]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner'], dtype=object)

In [134]:
df['Model_Name'].nunique()

303

In [172]:
Newf_df.head()

year  selling_price  km_driven    fuel seller_type transmission  \
0  2007          60000      70000  Petrol  Individual       Manual   
1  2007         135000      50000  Petrol  Individual       Manual   
2  2007         140000     125000  Petrol  Individual       Manual   
3  2017         365000      78000     CNG  Individual       Manual   
4  2007          60000      70000  Petrol  Individual       Manual   

         owner     Model_Name  
0  First Owner   94347.826087  
1  First Owner  144416.666667  
2  First Owner  117500.000000  
3  First Owner  365000.000000  
4  First Owner   94347.826087

In [173]:
def fuel_input(a):
    if a=='Petrol':
        return 0
    elif a=='CNG':
        return 1
    elif a=='Diesel':
        return 2
    elif a=='LPG':
        return 3
    
Newf_df['fuel']=Newf_df['fuel'].apply(fuel_input)

In [174]:
def seller_input(a):
    if a=='Individual':
        return 0
    elif a=='Dealer':
        return 1
    elif a=='Trustmark Dealer':
        return 2
    
Newf_df['seller_type']=Newf_df['seller_type'].apply(seller_input)

In [175]:
def trans_input(a):
    if a=='Manual':
        return 0
    elif a=='Automatic':
        return 1
    
Newf_df['transmission']=Newf_df['transmission'].apply(trans_input)

In [176]:
def owner_input(a):
    if a=='First Owner':
        return 0
    elif a=='Second Owner':
        return 1
    elif a=='Third Owner':
        return 2
    elif a=='Fourth & Above Owner':
        return 3
    
Newf_df['owner']=Newf_df['owner'].apply(owner_input)

In [177]:
Newf_df.head()

year  selling_price  km_driven  fuel  seller_type  transmission  owner  \
0  2007          60000      70000     0            0             0      0   
1  2007         135000      50000     0            0             0      0   
2  2007         140000     125000     0            0             0      0   
3  2017         365000      78000     1            0             0      0   
4  2007          60000      70000     0            0             0      0   

      Model_Name  
0   94347.826087  
1  144416.666667  
2  117500.000000  
3  365000.000000  
4   94347.826087

In [149]:
Newf_df['Model_Name']=Newf_df['Model_Name'].apply(lambda x: x/1000)

In [178]:
Newf_df.describe()

year  selling_price      km_driven         fuel  seller_type  \
count  1280.000000   1.280000e+03    1280.000000  1280.000000  1280.000000   
mean   2012.508594   3.424163e+05   63264.387500     0.656250     0.244531   
std       4.908698   2.308455e+05   46526.672122     0.944409     0.526441   
min    1992.000000   3.000000e+04    1000.000000     0.000000     0.000000   
25%    2009.000000   1.500000e+05   35000.000000     0.000000     0.000000   
50%    2014.000000   2.805000e+05   60000.000000     0.000000     0.000000   
75%    2017.000000   5.000000e+05   80000.000000     2.000000     0.000000   
max    2020.000000   1.100000e+06  806599.000000     3.000000     2.000000   

       transmission        owner    Model_Name  
count   1280.000000  1280.000000  1.279000e+03  
mean       0.040625     0.503906  3.423713e+05  
std        0.197497     0.753403  2.185715e+05  
min        0.000000     0.000000  3.500000e+04  
25%        0.000000     0.000000  1.444167e+05  
50%        0.000000     0.000000  2.930000e+05  
75%        0.000000     1.000000  5.114637e+05  
max        1.000000     3.000000  1.100000e+06

In [182]:
Newf_df['fuel'].unique()

array([0, 1, 2, 3], dtype=int64)

In [183]:
Newf_df['seller_type'].unique()

array([0, 1, 2], dtype=int64)

In [184]:
Newf_df['transmission'].unique()

array([0, 1], dtype=int64)

In [185]:
Newf_df['owner'].unique()

array([0, 1, 2, 3], dtype=int64)

In [188]:
Newf_df['Model_Name'].unique()

array([  94347.82608696,  144416.66666667,  117500.        ,
        365000.        ,  585000.        ,  887500.        ,
        259999.5       ,  305344.79310345,  123553.17021277,
        722500.        ,  346222.22222222,  310000.        ,
        552500.        ,  165727.27272727,  750000.        ,
        228333.33333333,  236666.66666667,  511463.73913043,
        110000.        ,  543333.16666667,   72636.36363636,
        565666.66666667,  226666.58333333,  738500.        ,
         85041.66666667,   89000.        ,  592500.        ,
        757250.        ,  210000.        ,  143608.69565217,
        550000.        ,  448724.10344828,  805000.        ,
        282000.        ,   86666.66666667,  296999.95238095,
        650000.        ,  115171.37142857,   75000.        ,
        310833.33333333,  200000.        ,  299545.45454545,
        100000.        ,  692500.        ,  783000.        ,
        800000.        ,   80000.        ,  267500.        ,
        142942.78571429,

In [189]:
Newf_df.fillna(Newf_df['Model_Name'].mean(),inplace=True)

In [179]:
from sklearn.ensemble import RandomForestRegressor

In [193]:
maruti_model=RandomForestRegressor(n_estimators=220,max_depth=8,min_samples_leaf=3,random_state=3)

In [194]:
maruti_model.fit(Newf_df.drop('selling_price',axis=1),y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=8, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=3,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=220, n_jobs=None, oob_score=False,
                      random_state=3, verbose=0, warm_start=False)

In [197]:
maruti_model.score(Newf_df.drop('selling_price',axis=1),y)

0.956697559667956

In [55]:
from sklearn.model_selection import GridSearchCV

In [144]:
rand_params={'n_estimators':[200,210,220],'max_depth':[8,9],'min_samples_leaf':[3,5],'random_state':[1,3,5,10]}

In [145]:
rand_grid=GridSearchCV(estimator=RandomForestRegressor(),param_grid=rand_params,cv=5,verbose=2)

In [190]:
rand_grid.fit(Newf_df.drop('selling_price',axis=1),y)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV] max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1, total=   1.0s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.9s remaining:    0.0s


[CV]  max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1, total=   1.0s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1, total=   0.9s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1, total=   0.7s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=1, total=   0.9s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=3 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=3, total=   0.9s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=3 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=3, total=   1.1s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=200, random_state=3 
[CV]  max_depth=8, min_samples_leaf=3, n_estim

[CV]  max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=5, total=   1.0s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=5 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=5, total=   0.9s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10, total=   1.0s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10, total=   0.9s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10, total=   1.3s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10 
[CV]  max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10, total=   1.1s
[CV] max_depth=8, min_samples_leaf=3, n_estimators=220, random_state=10 
[CV]  max_depth=8, min_samples_leaf=3

[CV]  max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3, total=   0.8s
[CV] max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3 
[CV]  max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3, total=   0.9s
[CV] max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3 
[CV]  max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3, total=   1.2s
[CV] max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3 
[CV]  max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3, total=   1.1s
[CV] max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3 
[CV]  max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=3, total=   1.2s
[CV] max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=5 
[CV]  max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=5, total=   0.9s
[CV] max_depth=8, min_samples_leaf=5, n_estimators=220, random_state=5 
[CV]  max_depth=8, min_samples_leaf=5, n_estim

[CV]  max_depth=9, min_samples_leaf=3, n_estimators=210, random_state=10, total=   1.0s
[CV] max_depth=9, min_samples_leaf=3, n_estimators=210, random_state=10 
[CV]  max_depth=9, min_samples_leaf=3, n_estimators=210, random_state=10, total=   0.9s
[CV] max_depth=9, min_samples_leaf=3, n_estimators=210, random_state=10 
[CV]  max_depth=9, min_samples_leaf=3, n_estimators=210, random_state=10, total=   1.3s
[CV] max_depth=9, min_samples_leaf=3, n_estimators=220, random_state=1 
[CV]  max_depth=9, min_samples_leaf=3, n_estimators=220, random_state=1, total=   1.1s
[CV] max_depth=9, min_samples_leaf=3, n_estimators=220, random_state=1 
[CV]  max_depth=9, min_samples_leaf=3, n_estimators=220, random_state=1, total=   0.9s
[CV] max_depth=9, min_samples_leaf=3, n_estimators=220, random_state=1 
[CV]  max_depth=9, min_samples_leaf=3, n_estimators=220, random_state=1, total=   1.0s
[CV] max_depth=9, min_samples_leaf=3, n_estimators=220, random_state=1 
[CV]  max_depth=9, min_samples_leaf=3, n_

[CV]  max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=3, total=   1.3s
[CV] max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5 
[CV]  max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5, total=   1.2s
[CV] max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5 
[CV]  max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5, total=   1.1s
[CV] max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5 
[CV]  max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5, total=   1.0s
[CV] max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5 
[CV]  max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5, total=   1.0s
[CV] max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5 
[CV]  max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=5, total=   1.4s
[CV] max_depth=9, min_samples_leaf=5, n_estimators=210, random_state=10 
[CV]  max_depth=9, min_samples_leaf=5, n_esti

[Parallel(n_jobs=1)]: Done 240 out of 240 | elapsed:  3.8min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0,
                                             criterion='mse', max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             max_samples=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='deprecated', n_jo

In [191]:
rand_grid.best_score_

0.9186619984621982

In [192]:
rand_grid.best_params_

{'max_depth': 8, 'min_samples_leaf': 3, 'n_estimators': 220, 'random_state': 3}

In [199]:
pickle.dump(maruti_model,open('maruti_model.pkl','wb'))